# fly.toml app configuration file for heidy-bot
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'heidy-bot'
primary_region = 'bog'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[mounts]
  source = "whatsapp_data"
  destination = "/app/whatsapp-sessions"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
