app = "heidy-bot"
primary_region = "bog"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[mounts]
  source = "whatsapp_data"
  destination = "/app/whatsapp-sessions"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"